server:
  max-http-request-header-size: 400000


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.173.186:3306/dr_food?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always

  profiles:
    include: secret

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace